### ISSUE TITLE
There is persistence?

### ISSUE THREAD

**Issue by axeladriant** [Daveawb/UnderStated#1]
> PS: Hi! Keep up with the good work.

**Comment by Daveawb** [comment]
Hi @kuroisuna

I haven't built in any type of persistence as I wanted to keep it lightweight. I acknowledge there is likely a high need for this capability but I do not want to tie it down to just Eloquent. I'm actively working on this project so I may put this in before a 1.0 release.

Thanks for the kind words!

**Comment by axeladriant** [comment]
Awesome, thanks for answering, I'll be watching this project
