### ISSUE TITLE
Hierarchical (HFSM)

### ISSUE THREAD

**Issue by antonkomarev** [Daveawb/UnderStated#8]
It will be great to be able to make Hierarchical states: https://en.wikipedia.org/wiki/UML_state_machine#Hierarchically_nested_states

**Comment by Daveawb** [comment]
@a-komarev I like the idea of being able to do this. Do you have any ideas on how this would be implemented?

**Comment by antonkomarev** [comment]
@Daveawb I've spent couple of days on research HFSM. Sadly, I haven't found any working examples.

In most of the cases I saw that people who started to implement HFSM in project ended with Behaviour Tree solution. I didn't want such a complex solution so I've decided to refactor states to fit classical FSM schema.

**Comment by Daveawb** [comment]
@a-komarev I think this would be quite a bit of work to attempt to implement with an opinionated design. For the time being I would very much stick to classical FSM structures. You could potentially grab the underlying state graph and nest any other data structures on nodes (or vertices for transitions) but this would become very difficult to manage without a well defined interface for interactions on the nested structures. Potentially handle / event handler methods could be expanded to allow for type resolution on arguments to make it more robust but still a lot of work would need to be done manually to facilitate this functionality.
